added password

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -37,7 +37,7 @@ jobs:
             - name: Terraform Apply
               run: terraform apply -auto-approve
               env:
-                TF_VAR_db_password: ${{ secrets.DB_PASSWORD }} # Pass the DB password secret
+                TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}  # Pass the DB password secret
                 TF_VAR_vpc_cidr: "10.0.0.0/16"  # Pass the VPC CIDR
                 TF_VAR_public_subnet_cidrs: '["10.0.1.0/24", "10.0.2.0/24"]'  # Pass the public subnet CIDRs
                 TF_VAR_private_subnet_cidrs: '["10.0.3.0/24", "10.0.4.0/24"]'  # Pass the private subnet CIDRs
@@ -45,7 +45,7 @@ jobs:
 
             - name: Set up error handling for cleanup
               run: |
-                trap 'echo "Error occurred or workflow canceled! Destroying all services..."; terraform destroy -auto-approve; exit 0' ERR
+                trap 'echo "Error occurred or workflow canceled! Destroying all services..."; terraform destroy -auto-approve -var "db_password=${{ secrets.DB_PASSWORD }}"; exit 0' ERR
 
             - name: Wait for API to be Ready
               run: sleep 5s
@@ -81,7 +81,7 @@ jobs:
                   --comment "Deploy habit tracker backend"
                 if [[ $? -ne 0 ]]; then
                   echo "Failed to clone repo or deploy the app! Destroying infrastructure.";
-                  terraform destroy -auto-approve;
+                  terraform destroy -auto-approve -var "db_password=${{ secrets.DB_PASSWORD }}";
                   exit 1;
                 fi
 
@@ -105,7 +105,7 @@ jobs:
 
             - name: Terraform Destroy (Always run)
               if: always()
-              run: terraform destroy -auto-approve
+              run: terraform destroy -auto-approve -var "db_password=${{ secrets.DB_PASSWORD }}"
               working-directory: ./
 
             - name: Exit pipeline after destruction
